name = "LinearHypothesisTest"
uuid = "911dceac-9954-403b-ac9e-c0705abf4ded"
authors = ["Elias L Ohneberg"]
version = "0.0.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[weakdeps]
FixedEffectModels = "9d5cd8c9-2029-5cab-9928-427838db53e3"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"

[extensions]
FE_LHT = "FixedEffectModels"
GLM_LHT = "GLM"

[compat]
Distributions = "0.25"
FixedEffectModels = "1"
GLM = "1"
julia = "1.9"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FixedEffectModels = "9d5cd8c9-2029-5cab-9928-427838db53e3"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["FixedEffectModels", "GLM", "CSV", "DataFrames", "Test"]
